### ISSUE TITLE
Update README about supported poetry versions

### ISSUE THREAD

**Issue by johnthagen** [enpaul/tox-poetry-installer#12]
The README says https://github.com/enpaul/tox-poetry-installer/#known-drawbacks-and-problems

> The plugin currently depends on poetry<1.1.0

But later it says https://github.com/enpaul/tox-poetry-installer/#developing

> This project requires Poetry version 1.0+

Also #10 references:

> Add trivial support for Poetry 1.1+

Does the README need to be updated/clarified? It wasn't clear if this works on the latest poetry (1.1.3) from reading it.

**Comment by enpaul** [comment]
Excellent point, these should be clarified.

The first note from the "known drawback" section is no longer accurate as of version 0.2.4 and should be removed from the readme. That's an oversight on my part.

The second note from the "developing" section refers to the version of poetry required for developing the project, not the actual dependency of the package. The package's poetry dependency is specified here, but that note gives the version that can be used for installing the development environment.

#10 is still open because I haven't thoroughly tested (to my satisfaction) that this works with both Poetry-1.0 and Poetry-1.1 just yet. That said I've been using this with 1.1.3 without a problem so it should work fine.

**Comment by enpaul** [comment]
@johnthagen Is [this updated note](https://github.com/enpaul/tox-poetry-installer#developing) clear enough do you think for the "developing" section? I removed the obsolete note from the "known drawbacks" section.

**Comment by johnthagen** [comment]
Yes, that looks good to me!
