### ISSUE TITLE
Consider documenting how to use tox requires field to add plugin dependency

### ISSUE THREAD

**Issue by johnthagen** [enpaul/tox-poetry-installer#13]
You could potentially document how to use the `[tox]` `requires` field to make installation of this plugin simpler. That would allow users to keep it out of the `dev-dependencies`.

For an example of how this works, see: https://github.com/sinoroc/tox-poetry-dev-dependencies#installation

**Comment by enpaul** [comment]
I'm not sure I would want to highlight this installation method. In fact I've considered having the plugin raise a warning if the `requires` parameter is found in the config, as it fundamentally breaks installing from a lockfile. The `requires` parameter uses the pip-based tox installation backend which means that any packages it specifies (and their dependencies) are subject to the conflict issues that the lockfile tries to avoid.

The main example I can see here is with tox itself: when tox checks the `config.requires` value it also [checks for the minversion of itself](https://github.com/tox-dev/tox/blob/7c103c8dfe04c67b90b69683f44ef399240df43a/src/tox/config/__init__.py), that way if the current version of tox is incompatible it will install a compatible tox in the provisioned virtualenv it creates. However, when it then installs `tox-poetry-installer` (which specifies tox as a dependency) pip will install the latest version of the `tox` package that is compatible with `tox-poetry-installer` with no regard for what version of tox is actually supposed to be in the virtualenv.

Full disclosure, I've never used the `requires` tox parameter (mostly because I keep tox in my poetry dev dependencies, so I haven't had a need for it) so if this is something that you think there's still value in having then I can definitely include it. I might want to put a warning about the above issue though next to that documentation.

**Comment by johnthagen** [comment]
This is a very good point (and probably worth mentioning in the docs for others!). Originally I had like the `requires` method because it cleaned up my Poetry environment (the tox plugin is only needed for tox, after all). But now as I think this through some more, if the goal is to have **all** dependencies locked, then it would be safer to also lock the `tox` plugin.

So perhaps the opposite of what I requested would be a good idea. Talk about `requires`, but advise against it.

Thanks for the detailed response!
