### ISSUE TITLE
LockedDepNotFoundError even though the dependency is in the lock file

### ISSUE THREAD

**Issue by brechtm** [enpaul/tox-poetry-installer#37]
I'm [trying out tox-poetry-installer on my project](https://github.com/brechtm/rinohtype/tree/wip/tox-poetry-installer), but I'm running into an issue:

```
$ tox -re py37
.package recreate: /Users/brechtm/Documents/Code/rinohtype/.tox/.package
.package installdeps: poetry-core>=1.0.0
py37 recreate: /Users/brechtm/Documents/Code/rinohtype/.tox/py37
ERROR: [tox-poetry-installer]: No version of locked dependency 'rinoh-typeface-texgyrecursor' found in the project lockfile
py37 inst: /Users/brechtm/Documents/Code/rinohtype/.tox/.tmp/package/1/rinohtype-0.5.0.dev0.tar.gz
____________________________________________ summary _____________________________________________
ERROR:   py37: LockedDepNotFoundError
```

As far as I can see, _rinoh-typeface-texgyrecursor_ is listed in the lock file. Perhaps the fact that this package also specifies my package under test as a dependency is relevant?

**Comment by enpaul** [comment]
Thank you for reporting this! This is indeed a bug with the dependency resolution processing. Because the package under test isn't actually in the lockfile it causes a `KeyError` when the plugin attempts to find the dependency of `rinoh-typeface-texgyrecursor`, which the plugin incorrectly interpolates into a `LocedDepNotFoundError`.

Having the package under test be a dependency of a locked dependency isn't a use case I had even thought of :smile: But it's absolutely something that can be supported. This should be a very simple patch to fix this.

**Comment by enpaul** [comment]
@brechtm When you get a chance can you try updating to `tox-poetry-installer 0.6.2` and see if the problem persists? That bugfix release should address the problem you're seeing here.

**Comment by brechtm** [comment]
It's working for me now. Thanks for the quick fix! ❤️
Now I can finally make use of GitHub's dependabot!
