### ISSUE TITLE
A way to emulate usedevelop=false? (i.e. install as wheel)

### ISSUE THREAD

**Issue by MarximusMaximus** [enpaul/tox-poetry-installer#74]
Is there a way to emulate how tox works when `usedevelop` is false? (It builds a wheel and installs it the "normal" way.) 

Some of my integration tests rely on verifying that things work properly when my package is installed "normally" as opposed to as "source/develop". (Primarily b/c the way to get certain reflection data is different between installed as a package vs installed as source/develop.)

Thanks!

**Comment by enpaul** [comment]
@MarximusMaximus I'm not 100% sure I understand what you mean by "installing it the normal way", are you referring to doing a PEP 517 wheel build and installing with Pip? If so, you can emulate this behavior like below:

```ini
# tox.ini

[tox]
isolated_build = true

[testenv]
skip_install = true
install_project_deps = true
commands =
  pip install . --no-deps
```

What this does:
* The [`skip_install`](https://tox.wiki/en/latest/config.html#conf-skip_install) option tells Tox to not install the package-under-test (or any of it's dependencies). 
* The `install_project_deps` option tells tox-poetry-installer to install the dependencies of the package-under-test, but not the package itself
* The `pip install . --no-deps` command causes Pip to do a PEP 517 install, where it builds the wheel (using `poetry-core`, as specified in your `pyproject.toml`) without any dependencies; this means the dependencies are installed using tox-poetry-installer instead of Pip so that you get the benefits of the lockfile.

If you try out this solution, can you let me know whether or not it works for your use case?

**Comment by MarximusMaximus** [comment]
Ah! I see, yes, this would work, and I could use the -e flag to explicitly do the envs where I need it to be not a wheel install. Thank you! I've had to switch some things around while using poetry 1.2.0 and pytest 7.1.3, so I cannot test this right now, unfortunately.
