### ISSUE TITLE
Use Poetry 1.3 with `[poetry]` extra

### ISSUE THREAD

**Issue by brandon-leapyear** [enpaul/tox-poetry-installer#78]
I believe the only thing blocking this is updating
```diff
-cleo = {version = "^1.0.0a5", optional = true, allow-prereleases = true}
+cleo = {version = "^2.0.0", optional = true, allow-prereleases = true}
-poetry = {version = "^1.2.0", optional = true}
+poetry = {version = "^1.3.0", optional = true}
```

**Comment by nejch** [comment]
Default ranges created by poetry when adding deps are almost always too restrictive for libraries like this plugin. It mostly only has applications in mind for default behavior IMO.

Maybe a more open range would make sense? Otherwise library users will always have conflicts if they have other dependencies. See also https://github.com/enpaul/tox-poetry-installer/issues/82 which is a similar problem although that's a major release so makes a bit more sense.

**Comment by enpaul** [comment]
Hi @brandon-leapyear sorry for the delay in response here. This is a good thing flag, I'll work on getting this out soon.

@nejch The restrictive dependency specification is one of the driving reasons behind #2 . Unfortunately that issue is currently blocked right now, but once done this plugin will drop a dependency on Poetry entirely.

**Comment by nejch** [comment]
Thanks for looking into this @enpaul! Since https://github.com/enpaul/tox-poetry-installer/issues/82 will probably stay blocked for a while, does it make sense to release this on pypi so people can use poetry 1.3 for the time being?
